apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/warrenbailey/spring-issue-3452-1:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/warrenbailey/spring-issue-3452-1:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: spring-issue-3452-1
        chartPath: charts/spring-issue-3452-1
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/warrenbailey/spring-issue-3452-1'
          image.tag: '{{.DIGEST_HEX}}'
